version: '3'

services:
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/_frontend
      - media_volume:/usr/src/app/upload
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web

  web:
    build: .
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    expose:
      - "8000"
    env_file:
      - ./.env.prod
    depends_on:
      - db
      
  db:
    image: mysql:8.0
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      # MYSQL_ROOT_PASSWORD: '!Ghgh1234'
      MYSQL_DATABASE: hirestaurant.dev
      MYSQL_USER: admin
      MYSQL_PASSWORD: '!Ghgh1234'
      TZ: Asia/Seoul 
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci  # 오타 수정
    volumes:
      - mysql_data:/var/lib/mysql 
    env_file:
      - ./.env.prod


volumes:
  mysql_data:
  static_volume:
  media_volume: