version: "3"

services:
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/_frontend
      - media_volume:/usr/src/app/upload
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web

  web:
    build: .
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/_frontend
      - media_volume:/usr/src/app/upload
      - ./:/usr/src/app/
    expose:
      - "8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    ports:
      - "3307:3306"
    env_file:
      - ./.env.prod
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci # 오타 수정
      - --local-infile=1
      - --bind-address=0.0.0.0
      - --secure-file-priv=""
    volumes:
      - ./path/to/my.cnf:/etc/mysql/my.cnf
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  static_volume:
  media_volume:
