# Generated by Django 4.2.4 on 2024-01-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirestaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_image2',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_pics'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_image3',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_pics'),
        ),
    ]
