# Generated by Django 4.2.4 on 2023-09-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirestaurant', '0002_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
    ]
