# Generated by Django 4.2.4 on 2024-01-11 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hirestaurant', '0003_alter_restaurant_restaurant_image1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
