# Generated by Django 4.2.4 on 2023-12-14 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hirestaurant', '0004_category_tag_restaurant_category_restaurant_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hirestaurant.category'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='tags',
            field=models.ManyToManyField(blank=True, to='hirestaurant.tag'),
        ),
    ]
