# Generated by Django 4.2.4 on 2024-01-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirestaurant', '0004_remove_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_image1',
            field=models.ImageField(upload_to='restaurant_pics'),
        ),
    ]
