# Generated by Django 4.2.4 on 2023-09-07 14:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hirestaurant', '0004_remove_restaurant_restaurant_link_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image1',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='review_pics'),
        ),
        migrations.AddField(
            model_name='review',
            name='image2',
            field=models.ImageField(blank=True, upload_to='review_pics'),
        ),
        migrations.AddField(
            model_name='review',
            name='image3',
            field=models.ImageField(blank=True, upload_to='review_pics'),
        ),
    ]
