# Generated by Django 4.2.4 on 2023-12-14 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hirestaurant', '0005_alter_restaurant_category_alter_restaurant_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hirestaurant.category'),
        ),
    ]
