# Generated by Django 4.2.4 on 2023-09-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirestaurant', '0005_user_following_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='dt_updatea',
        ),
        migrations.AddField(
            model_name='comment',
            name='dt_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
