# Generated by Django 4.2.4 on 2023-09-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirestaurant', '0005_review_image1_review_image2_review_image3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image1',
            field=models.ImageField(upload_to='review_pics'),
        ),
    ]
