# Generated by Django 4.2.4 on 2023-09-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirestaurant', '0006_remove_comment_dt_updatea_comment_dt_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='dt_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='dt_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
