# Generated by Django 4.2.4 on 2023-09-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirestaurant', '0007_alter_comment_dt_updated_alter_like_dt_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
