# Generated by Django 4.2.4 on 2023-09-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirestaurant', '0008_comment_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='dt_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
